### ISSUE TITLE
Fly.io Deployment

### ISSUE THREAD

**Issue by cdirks4** [open-biz/OpenBookLM#10]
## Description 
Set up production deployment pipeline using Fly.io platform.

## Technical Requirements
- Fly.io application configuration
- CI/CD pipeline
- Production environment setup
- Monitoring and logging

## Tasks
- [ ] Create Fly.io Configuration
```toml
# fly.toml
[env]
  PORT = "8080"
  NODE_ENV = "production"

[services]
  internal_port = 8080
  protocol = "tcp"

[metrics]
  port = 9091
  path = "/metrics"
```

- [ ] Set Up GitHub Actions
```yaml
# .github/workflows/deploy.yml
name: Deploy to Fly.io
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
```

- [ ] Configure Production Environment
- [ ] Set Up Monitoring
- [ ] Add Error Tracking

## Acceptance Criteria
- Application deploys successfully
- CI/CD pipeline works
- Environment variables are secure
- Monitoring is in place
- Error tracking is functional

## Required Environment Variables
```env
FLY_API_TOKEN=your_fly_api_token
DATABASE_URL=your_production_db_url
REDIS_URL=your_production_redis_url
```

## Documentation
- Deployment process
- Environment configuration
- Monitoring setup
- Troubleshooting guide
